name: Unit test

on:
  release:
    types: [ created ]
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - ".github/workflows/unit-tests.yaml"

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: make tests
